title: Fatal Error
email: fatal-error-podcast@googlegroups.com
description: Fatal Error was a podcast that ran from 2016 to 2018
  about iOS and Swift development, hosted by Chris Dzombak and Soroush
  Khanlou.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fatalerror.fm"
real_url: "https://fatalerror.fm"
permalink: /:categories/:year/:i_month/:i_day/:title
feed:
  path: rss.xml

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-remote-theme
remote_theme: jekyll/minima
exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - vendor
  - rss_scraper.py
  - wordpress.xml
  - episodes.rss
