---
title: Fatal Error
author:
  name: "Soroush Khanlou & Chris Dzombak"
  email: fatal-error-podcast@googlegroups.com
description: Fatal Error is a podcast about software development, hosted by Soroush Khanlou and Chris Dzombak.
baseurl: ""  # the subpath of your site, e.g. /blog
url: "https://fatalerror.fm"
real_url: "https://fatalerror.fm"
permalink: /:categories/:year/:i_month/:i_day/:title
feed:
  path: rss.xml

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-remote-theme
remote_theme: jekyll/minima
exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
  - rss_scraper.py
  - wordpress.xml
  - episodes.rss
  - scripts
